### ISSUE TITLE
Problems when running the Quickstart example

### ISSUE THREAD

**Issue by mgarbade** [dribnet/plat#3]
On running the third command of the quickstart example, I'm getting the following error:
```
> plat sample --model celeba_64.discgen
Couldn't import dot_parser, loading of dot files will not be possible.
Model celeba_64.discgen will be downloaded. Continue? [Y/n]y
Downloading celeba_64_v1.0.0.discgen.gz

/tmp/tmpfYWrkQ/celeba_64_v1.0.0.discgen.gz: 100% [=========================] Time: 0:00:10  12.9 MiB/s
Decompressing celeba_64.discgen
Installing celeba_64.discgen
Loading DiscGenModel interface from discgen.interface
==> Failed to load supporting class discgen.interface.DiscGenModel
==> Check that package discgen is installed
(exception was: cannot import name bn)
```

Besides I'm merely interested in the way z is sampled for the GAN training. Maybe someone could kindly point me to the respective position in the code?

**Comment by dribnet** [comment]
hi - will try to look at this today.

the discgen model is a VAE based model (not a GAN) and is sampled from a gaussian prior. this library supports both gaussian and uniform priors. [here is location in the code](https://github.com/dribnet/plat/blob/32a57e146f8a36b9dfcb49192087fc76a2974f02/plat/sampling.py#L67-L70).

**Comment by mgarbade** [comment]
Hmm I'm trying to train some GANs and I wondered how you sample the initializing z vector for the GAN training, thats why I tried to walk through your code. According to a [NIPS talk by Chintalla](https://youtu.be/X1mUN6dD8uE?t=8m9s) you were somehow using random points from a sphere as values for z during training? I tried to look it up in your [respective paper](https://arxiv.org/pdf/1609.04468.pdf), but there it was only stated to use points on a sphere when doing interpolation between two GAN images. (Sorry if this is offtopic for this github thread)

Also found [this question](https://stats.stackexchange.com/q/276825/89048?sem=2) on "Cross Validated" which is the same as mine. Sorry to bother you with this, but  I'd love to improve my GAN results ...

**Comment by dribnet** [comment]
Hi - sorry for not catching your question earlier.

My paper mainly covers how to sample from a GAN (or VAE) once it is trained, and don't really cover issues in training process itself. GANs generally have a gaussian prior, but sometimes they have a uniform prior instead - in either case you will have "tentpole" issues when interpolating between two points if you use linear interpolation - so slerp corrects for this somewhat in both cases.

Hope that helps. If you are still having troubles with this, feel free to followup again.
